# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

prox_lasso <- function(u, dim_u, unreg_p, tau_lam) {
    .Call(`_free_prox_lasso`, u, dim_u, unreg_p, tau_lam)
}

REE_KM <- function(beta, p, reg_p, U, tau, alpha, penalty, lambda1, maxit, tol_U, tol_beta, verbose = FALSE) {
    .Call(`_free_REE_KM`, beta, p, reg_p, U, tau, alpha, penalty, lambda1, maxit, tol_U, tol_beta, verbose)
}

